services:
  - type: web
    name: tradingview-webhook-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --bind 0.0.0.0:8000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
